### ISSUE TITLE
Storybook broken for "auth" library

### ISSUE THREAD

**Issue by ZenSoftware** [ZenSoftware/zen#30]
Getting an error starting Storybook after upgrading from Storybook from 7.2.1 to 7.3.2 for the "auth" library.  Though, the "components" library has storybook working just fine.  I think it has something to do with Jest & Storybook.

```
ReferenceError: beforeEach is not defined
    at ./node_modules/.pnpm/@angular+core@16.2.1_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/testing.mjs (http://localhost:4400/vendors-node_modules_pnpm_angular_material_16_2_1__angular_animations_16_2_1__angular_cdk_16_-35a127.iframe.bundle.js:107726:1)
    at __webpack_require__ (http://localhost:4400/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:4400/runtime~main.iframe.bundle.js:338:21)
    at ./node_modules/.pnpm/@angular+router@16.2.1_@angular+common@16.2.1_@angular+core@16.2.1_@angular+platform-browser@16.2.1_rxjs@7.8.1/node_modules/@angular/router/fesm2022/testing.mjs (http://localhost:4400/vendors-node_modules_pnpm_angular_material_16_2_1__angular_animations_16_2_1__angular_cdk_16_-35a127.iframe.bundle.js:122215:79)
    at __webpack_require__ (http://localhost:4400/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:4400/runtime~main.iframe.bundle.js:338:21)
    at ./libs/auth/.storybook/preview.ts (http://localhost:4400/main.iframe.bundle.js:382:81)
    at __webpack_require__ (http://localhost:4400/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:4400/runtime~main.iframe.bundle.js:338:21)
    at Object.getProjectAnnotations [as nextFn] (http://localhost:4400/main.iframe.bundle.js:2040:2969)
```

**Comment by ZenSoftware** [comment]
Fixed with release of v11.1.0
